---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/blogs
  label: Blogs
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/portofolios
  label: Portofolio's
  create: documents
  match: "/*"
  templates:
  - blog-post
- type: heading
  label: Data
- type: directory
  path: data
  label: Authors
  create: all
  match: authors.yml
- type: directory
  path: data
  label: Locations
  create: all
  match: locations.yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
